name: Flutter_Scaffold
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
# 需要Flutter 2.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  retrofit: ^2.0.0
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  json_serializable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^2.0.0
  build_runner: any

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

