class Autogenerated {
  String id;
  String createdAt;
  String name;
  String avatar;

  Autogenerated({this.id, this.createdAt, this.name, this.avatar});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    createdAt = json['createdAt'];
    name = json['name'];
    avatar = json['avatar'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['createdAt'] = this.createdAt;
    data['name'] = this.name;
    data['avatar'] = this.avatar;
    return data;
  }

  @override
  String toString() {
    return 'Autogenerated{id: $id, createdAt: $createdAt, name: $name, avatar: $avatar}';
  }
}

abstract class Base{
  fromJson(Map<String, dynamic> json) {

  }
}

class BaseResponse<T>{

  T t;

  BaseResponse();

  void fun(){
    if(t is Base){

    }
  }

}